version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: sulabh4udacity/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: sulabh4udacity/rest-api-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: sulabh4udacity/rest-api-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: sulabh4udacity/udacity-frontend
